force-app/main/default/objects/Software_Course__c/Software_Course__c.object-meta.xml
<CustomObject>
    <label>Software Course</label>
    <nameField>
        <label>Software Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Software_Course__c.field-meta.xml
<CustomField>
    <fullName>Software_Course__c</fullName>
    <label>Software Course</label>
    <referenceTo>Software_Course__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Roll_No__c.field-meta.xml
<CustomField>
    <fullName>Student_Roll_No__c</fullName>
    <label>Student Roll No</label>
    <length>19</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Students.cls
public class Students {
    public static void Students(){
        Student__c s = new Student__c();

s.Name = 'Karthikeyan';          // Student Name
s.Student_Roll_No__c = '22IT001';
s.Number__c = '9876543210';
s.Email__c = 'karthik@gmail.com';
s.DOB__c = Date.newInstance(2005, 7, 6);
s.Gender__c = 'Male';
        s.Software_Course__c = 'SalesForce';
insert s;
        
        
Student__c s1 = new Student__c();
s1.Name = 'Melwin';         
s1.Student_Roll_No__c = '22IT002';
s1.Number__c = '9876543990';
s1.Email__c = 'melwin@gmail.com';
s1.DOB__c = Date.newInstance(2005, 12, 27);
s1.Gender__c = 'Male';
 s1.Software_Course__c = 'SalesForce';
insert s1;
        
List<Student__c> studentList = new List<Student__c>();
studentList.add(s);
studentList.add(s1);
insert studentList;
    }

}